import { useCallback } from 'react';
import { Link, useParams } from 'react-router-dom';
import { productsApi } from '../../api/products';
import { useResource } from '../../hooks/useResource';
import { ErrorAlert, PageHeader, Skeleton, StockBadge, TableRegion, priceLabel } from '../../components/ui';
export function ProductDetail() {
  const { id } = useParams(); const load = useCallback(() => productsApi.detail(id!), [id]); const r = useResource(load); const p = r.data;
  return <><Link className="back" to="/products">← Back to products</Link>{r.loading ? <Skeleton kind="form" /> : r.error ? <ErrorAlert message={r.error} retry={r.retry} /> : p && <><PageHeader title={p.productName} description={`${p.sku} · ${p.category}`} /><section className="card"><dl className="product-summary"><div><dt>Current stock</dt><dd><strong>{p.currentStock}</strong> <StockBadge stock={p.currentStock} minimum={p.minimumStockAlertQuantity} /></dd></div><div><dt>Unit price</dt><dd className="number-value">{priceLabel(p.unitPrice)}</dd></div><div><dt>Minimum stock alert</dt><dd>{p.minimumStockAlertQuantity}</dd></div><div><dt>Warehouse location</dt><dd>{p.warehouseLocation}</dd></div></dl></section><section className="card list-card history-card"><div className="filters"><h2>Stock movement history</h2></div>{!p.stockMovements?.length ? <div className="empty"><h3>No stock movements yet</h3><p>Recorded stock adjustments and confirmed dispatches will appear here.</p></div> : <TableRegion name="Stock movement history"><table className="movement-table"><thead><tr><th>Type</th><th className="numeric">Quantity</th><th>Reason</th><th>Date</th></tr></thead><tbody>{p.stockMovements.map(m => <tr key={m.id}><td><span className={`badge ${m.movementType === 'IN' ? 'active' : 'warning'}`}>{m.movementType === 'IN' ? 'IN · Added' : 'OUT · Removed'}</span></td><td className="numeric">{m.quantityChanged}</td><td>{m.reason}</td><td>{new Date(m.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table></TableRegion>}</section></>}</>;
}
