import { randomUUID } from 'node:crypto';
import {Prisma,ChallanStatus,MovementType} from '@prisma/client';import {prisma} from '../config/database.js';import {AppError} from '../utils/app-error.js';import type {CreateChallan} from '../validators/challan.validator.js';
const notFound=()=>new AppError(404,'CHALLAN_NOT_FOUND','Challan not found');
const include={customer:true,createdBy:{select:{id:true,name:true,email:true,role:true}},items:true} satisfies Prisma.ChallanInclude;
export async function create(data:CreateChallan,actor:string){const ids=[...new Set(data.items.map(i=>i.productId))];if(ids.length!==data.items.length)throw new AppError(400,'VALIDATION_ERROR','Duplicate products are not allowed');return prisma.$transaction(async tx=>{const customer=await tx.customer.findUnique({where:{id:data.customerId}});if(!customer)throw new AppError(404,'CUSTOMER_NOT_FOUND','Customer not found');const products=await tx.product.findMany({where:{id:{in:ids}}});if(products.length!==ids.length)throw new AppError(404,'PRODUCT_NOT_FOUND','Product not found');const map=new Map(products.map(p=>[p.id,p]));const number=`CH-${randomUUID()}`;return tx.challan.create({data:{challanNumber:number,customerId:data.customerId,totalQuantity:data.items.reduce((a,i)=>a+i.quantity,0),createdById:actor,items:{create:data.items.map(i=>{const p=map.get(i.productId)!;return {productId:p.id,productNameSnapshot:p.productName,skuSnapshot:p.sku,unitPriceSnapshot:p.unitPrice,quantity:i.quantity};})}},include});});}
export async function list(q:{page:number;limit:number;status?:'DRAFT'|'CONFIRMED'|'CANCELLED'}){const where={...(q.status?{status:q.status as ChallanStatus}:{})};const [challans,total]=await prisma.$transaction([prisma.challan.findMany({where,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{createdAt:'desc'},include}),prisma.challan.count({where})]);return {challans,pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
export async function detail(id:string){const c=await prisma.challan.findUnique({where:{id},include});if(!c)throw notFound();return c;}
export async function confirm(id:string,actor:string){return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Challan" WHERE id = ${id} FOR UPDATE`;const c=await tx.challan.findUnique({where:{id},include:{items:true}});if(!c)throw notFound();if(c.status!==ChallanStatus.DRAFT)throw new AppError(409,'INVALID_CHALLAN_STATUS','Only draft challans can be confirmed');if(!c.items.length||c.items.some(i=>!i.productId))throw new AppError(409,'INSUFFICIENT_STOCK','A challan product is no longer available');const productIds=c.items.map(i=>i.productId!).filter(Boolean).sort(); await tx.$queryRaw`SELECT id FROM "Product" WHERE id IN (${Prisma.join(productIds)}) ORDER BY id FOR UPDATE`;const products=await tx.product.findMany({where:{id:{in:productIds}}});for(const i of c.items){const p=products.find(x=>x.id===i.productId);if(!p||p.currentStock<i.quantity)throw new AppError(409,'INSUFFICIENT_STOCK',`Insufficient stock for ${i.skuSnapshot}`);}for(const i of c.items){await tx.product.update({where:{id:i.productId!},data:{currentStock:{decrement:i.quantity}}});await tx.stockMovement.create({data:{productId:i.productId!,quantityChanged:i.quantity,movementType:MovementType.OUT,reason:`Challan ${c.challanNumber}`,createdById:actor}});}return tx.challan.update({where:{id},data:{status:ChallanStatus.CONFIRMED,confirmedAt:new Date()},include});});}
export async function cancel(id:string){return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Challan" WHERE id = ${id} FOR UPDATE`;const c=await tx.challan.findUnique({where:{id}});if(!c)throw notFound();if(c.status!==ChallanStatus.DRAFT)throw new AppError(409,'INVALID_CHALLAN_STATUS','Only draft challans can be cancelled');return tx.challan.update({where:{id},data:{status:ChallanStatus.CANCELLED,cancelledAt:new Date()},include});});}

