import { Prisma, MovementType } from '@prisma/client'; import { prisma } from '../config/database.js'; import { AppError } from '../utils/app-error.js'; import type { ProductCreate,ProductUpdate,ProductQuery,MovementInput,MovementQuery } from '../validators/product.validator.js'; import { safeUserSelect } from './auth.service.js';
const nf=()=>new AppError(404,'PRODUCT_NOT_FOUND','Product not found');
export async function listProducts(q:ProductQuery){const where:Prisma.ProductWhereInput=q.search?{OR:[{productName:{contains:q.search,mode:'insensitive'}},{sku:{contains:q.search,mode:'insensitive'}},{category:{contains:q.search,mode:'insensitive'}},{warehouseLocation:{contains:q.search,mode:'insensitive'}}]}:{}; if(q.category) where.category=q.category; const [products,total]=await prisma.$transaction([prisma.product.findMany({where,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{createdAt:'desc'}}),prisma.product.count({where})]); return {products,pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
export async function createProduct(data:ProductCreate){try{return await prisma.product.create({data});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')throw new AppError(409,'DUPLICATE_SKU','SKU already exists');throw e;}}
export async function getProduct(id:string){const p=await prisma.product.findUnique({where:{id},include:{stockMovements:{orderBy:{createdAt:'desc'},include:{createdBy:{select:safeUserSelect}}}}});if(!p)throw nf();return p;}
export async function updateProduct(id:string,data:ProductUpdate){try{return await prisma.product.update({where:{id},data});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&(e.code==='P2025'))throw nf();if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')throw new AppError(409,'DUPLICATE_SKU','SKU already exists');throw e;}}
export async function listMovements(q:MovementQuery){const where:Prisma.StockMovementWhereInput={...(q.productId?{productId:q.productId}:{}),...(q.movementType?{movementType:q.movementType as MovementType}:{})};const [movements,total]=await prisma.$transaction([prisma.stockMovement.findMany({where,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{createdAt:'desc'},include:{product:true,createdBy:{select:safeUserSelect}}}),prisma.stockMovement.count({where})]);return {movements,pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
export async function adjustStock(id:string,actor:string,data:MovementInput){return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Product" WHERE id = ${id} FOR UPDATE`;const p=await tx.product.findUnique({where:{id}});if(!p)throw nf();if(data.movementType==='OUT'&&p.currentStock<data.quantityChanged)throw new AppError(409,'INSUFFICIENT_STOCK','Insufficient stock');const next=p.currentStock+(data.movementType==='IN'?data.quantityChanged:-data.quantityChanged);if(next>2147483647)throw new AppError(400,'VALIDATION_ERROR','Stock exceeds the supported maximum');const updated=await tx.product.update({where:{id},data:{currentStock:next}});await tx.stockMovement.create({data:{productId:id,quantityChanged:data.quantityChanged,movementType:data.movementType as MovementType,reason:data.reason,createdById:actor}});return updated;});}


