import { useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { challansApi, type Challan } from '../../api/challans';
import { customersApi } from '../../api/customers';
import { productsApi } from '../../api/products';
import { errorMessage } from '../../api/client';
import { ErrorAlert,Loading,PageHeader,Skeleton,TableRegion,priceLabel } from '../../components/ui';
import { useAuth } from '../../contexts/AuthContext';
import type { Customer,Product } from '../../types';
const writable=(role?:string)=>role==='ADMIN'||role==='SALES';
export function ChallanBadge({status}:{status:Challan['status']}){return <span className={`badge ${status==='CONFIRMED'?'active':status==='DRAFT'?'lead':'inactive'}`}>{status}</span>}
export function ChallanList(){
 const {user}=useAuth();const [page,setPage]=useState(1),[status,setStatus]=useState(''),[retry,setRetry]=useState(0);
 const [data,setData]=useState<Awaited<ReturnType<typeof challansApi.list>>>(),[error,setError]=useState('');
 useEffect(()=>{let active=true;setData(undefined);setError('');challansApi.list(page,status).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(errorMessage(e))});return()=>{active=false}},[page,status,retry]);
 return <><PageHeader title="Sales challans" description="Draft and confirmed dispatch records">{writable(user?.role)&&<Link className="button primary" to="/challans/new">Create challan</Link>}</PageHeader><section className="card list-card"><div className="filters"><label className="status-filter">Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['DRAFT','CONFIRMED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></label></div><ErrorAlert message={error} retry={()=>setRetry(retry+1)}/>{!data&&!error?<Skeleton/>:data&&<>{!data.challans.length?<div className="empty"><h2>No challans found.</h2><p>{status ? "Try another status or show all statuses." : "Create a draft to prepare your first dispatch."}</p>{status ? <button onClick={()=>{setStatus('');setPage(1)}}>Clear filter</button> : writable(user?.role) && <Link to="/challans/new">Create your first draft</Link>}</div>:<TableRegion name="Challan table"><table className="challan-table"><thead><tr><th>Challan</th><th>Customer</th><th className="numeric">Quantity</th><th>Status</th><th>Created</th></tr></thead><tbody>{data.challans.map(c=><tr key={c.id}><td><Link to={`/challans/${c.id}`}>{c.challanNumber}</Link></td><td>{c.customer.customerName}</td><td className="numeric">{c.totalQuantity}</td><td><ChallanBadge status={c.status}/></td><td>{new Date(c.createdAt).toLocaleString()}</td></tr>)}</tbody></table></TableRegion>}<div className="pagination"><span>Page {page} of {Math.max(1,data.pagination.totalPages)}</span><div className="actions"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)}>Next</button></div></div></>}</section></>
}
function Summary({c}:{c:Challan}){return <><p>{c.customer.customerName} · Total quantity: {c.totalQuantity}</p><TableRegion name="Challan line items"><table className="summary-table"><thead><tr><th>Product</th><th>SKU</th><th className="numeric">Unit price</th><th className="numeric">Quantity</th></tr></thead><tbody>{c.items.map(i=><tr key={i.id}><td>{i.productNameSnapshot}</td><td>{i.skuSnapshot}</td><td className="numeric">{priceLabel(i.unitPriceSnapshot)}</td><td className="numeric">{i.quantity}</td></tr>)}</tbody></table></TableRegion></>}
function Confirm({c,onDone}:{c:Challan;onDone:(c:Challan)=>void}){
 const [action,setAction]=useState<'confirm'|'cancel'|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const lock=useRef(false),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(action)dialog.current?.showModal();else dialog.current?.close()},[action]);
 const cancelling=action==='cancel';
 async function submit(){
  if(lock.current||!action)return;
  lock.current=true;setBusy(true);setError('');
  try{onDone(await challansApi[action](c.id));setAction(null)}
  catch(e){setError(errorMessage(e))}
  finally{lock.current=false;setBusy(false)}
 }
 function open(next:'confirm'|'cancel'){if(lock.current)return;setError('');setAction(next)}
 return <><div className="actions challan-actions">
  <button className="primary" disabled={busy} onClick={()=>open('confirm')}>Confirm Challan</button>
  <button className="danger-outline" disabled={busy} onClick={()=>open('cancel')}>Cancel Challan</button>
 </div><dialog ref={dialog} className="challan-dialog" aria-labelledby="challan-action-title" onCancel={e=>{if(busy)e.preventDefault();else setAction(null)}}>
  <h2 id="challan-action-title">{cancelling?'Cancel this draft challan?':'Confirm challan?'}</h2>
  <p>{cancelling?'This draft will be marked CANCELLED and cannot be confirmed later. Stock will not change.':'Confirmation reduces stock for every line and cannot be reversed here.'}</p>
  <Summary c={c}/><ErrorAlert message={error}/>
  <div className="form-footer"><button disabled={busy} onClick={()=>setAction(null)}>Back</button>
   <button className={cancelling?'danger-outline':'primary'} disabled={busy} onClick={submit}>{busy?(cancelling?'Cancelling…':'Confirming…'):(cancelling?'Yes, cancel challan':'Confirm stock deduction')}</button>
  </div>
 </dialog></>
}export function ChallanDetail(){const {id}=useParams();const {user}=useAuth();const [success,setSuccess]=useState('');const [c,setC]=useState<Challan>(),[error,setError]=useState(''),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;setError('');challansApi.detail(id!).then(x=>{if(active)setC(x)}).catch(e=>{if(active)setError(errorMessage(e))});return()=>{active=false}},[id,retry]);return <><Link className="back" to="/challans">← Back to challans</Link><ErrorAlert message={error} retry={()=>setRetry(retry+1)}/>{!c&&!error?<Loading/>:c&&<><PageHeader title={c.challanNumber}><ChallanBadge status={c.status}/></PageHeader><section className="card stack">{success&&<div role="status" className="alert success">{success}</div>}<Summary c={c}/><p>Created by {c.createdBy.name} · {new Date(c.createdAt).toLocaleString()}</p>{c.status==='DRAFT'&&writable(user?.role)&&<Confirm c={c} onDone={updated=>{setC(updated);setSuccess(updated.status==='CONFIRMED'?'Challan confirmed. Stock deduction recorded.':'Challan cancelled. Stock has not changed.')}}/>}</section></>}</>}
export function ChallanCreate(){
 const [customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const [customerId,setCustomer]=useState(''),[items,setItems]=useState([{key:0,productId:'',quantity:1}]),[busy,setBusy]=useState(false),[saved,setSaved]=useState<Challan>();const lock=useRef(false),sequence=useRef(1);
 useEffect(()=>{let active=true;setLoading(true);setError('');async function load(){const cs:Customer[]=[],ps:Product[]=[];for(let page=1;;page++){const r=await customersApi.list({page,limit:100});cs.push(...r.customers);if(page>=r.pagination.totalPages)break}for(let page=1;;page++){const r=await productsApi.list({page,limit:100});ps.push(...r.products);if(page>=r.pagination.totalPages)break}if(active){setCustomers(cs);setProducts(ps)}}load().catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[retry]);
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;if(new Set(items.map(i=>i.productId)).size!==items.length){setError('Choose each product only once.');return}lock.current=true;setBusy(true);setError('');try{setSaved(await challansApi.create({customerId,items:items.map(({productId,quantity})=>({productId,quantity}))}))}catch(e){setError(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 if(saved)return <><PageHeader title={saved.challanNumber}><ChallanBadge status={saved.status}/></PageHeader><section className="card stack"><div className="alert success" role="status">{saved.status==='DRAFT'?'Draft saved. Stock has not changed.':saved.status==='CANCELLED'?'Challan cancelled. Stock has not changed.':'Challan confirmed by the server.'}</div><Summary c={saved}/>{saved.status==='DRAFT'&&<Confirm c={saved} onDone={setSaved}/>}<Link to={`/challans/${saved.id}`}>View challan detail</Link><Link to="/challans">Back to challans</Link></section></>;
 return <><Link className="back" to="/challans">← Back to challans</Link><PageHeader title="Create challan" description="Save a draft, then review and confirm its stock deduction."/><ErrorAlert message={error} retry={()=>setRetry(retry+1)}/>{loading?<Skeleton kind="form"/>:<form onSubmit={save} className="card stack"><fieldset disabled={busy} className="stack"><label>Customer *<select required value={customerId} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.customerName} — {c.businessName}</option>)}</select></label>{!customers.length&&<p>No customers available. Add a customer first.</p>}{items.map((item,index)=>{const p=products.find(p=>p.id===item.productId);return <div className="challan-line" key={item.key}><label>Product {index+1} *<select required value={item.productId} onChange={e=>setItems(items.map(i=>i.key===item.key?{...i,productId:e.target.value}:i))}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id} disabled={items.some(i=>i.key!==item.key&&i.productId===p.id)}>{p.productName} — {p.sku}</option>)}</select></label><label>Quantity *<input required type="number" min="1" max="2147483647" step="1" value={item.quantity} onChange={e=>setItems(items.map(i=>i.key===item.key?{...i,quantity:e.target.valueAsNumber}:i))}/></label><dl className="line-facts"><div><dt>Available stock</dt><dd>{p?.currentStock??'—'}</dd></div><div><dt>Unit price</dt><dd>{p ? priceLabel(p.unitPrice) : '—'}</dd></div></dl><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter(i=>i.key!==item.key))}>Remove row {index+1}</button></div>})}{!products.length&&<p>No products available. Add a product first.</p>}<button type="button" disabled={items.length>=100} onClick={()=>setItems([...items,{key:sequence.current++,productId:'',quantity:1}])}>Add product row</button><div className="form-footer challan-footer"><strong>Total quantity: {items.reduce((sum,i)=>sum+(Number.isFinite(i.quantity)?i.quantity:0),0)}</strong><div className="actions"><Link className="button" to="/challans">Cancel</Link><button className="primary" disabled={busy||!customers.length||!products.length}>{busy?'Saving…':'Save Draft'}</button></div></div></fieldset></form>}</>
}

